version: '3.9'

services:
  database:
    image: postgres:16.3
    container_name: starter_kit
    ports:
      - "5433:5432"

    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: starter_kit
      TZ: UTC
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

networks:
  my:
    driver: bridge

